 pipeline {
   agent any

   tools {nodejs "nodejs"}

   stages {
     stage("Initializing") {
       steps {
         sh 'npm install' 
       }
     }

     stage("Running Tests") {
       steps { 
           sh 'npx codeceptjs run --steps --plugins allure'
       }
     }
   }

 }